[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--no-audit --no-optional"
  NODE_ENV = "production"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 